[test]
coverage = true
pathIgnorePatterns = [
  "apps/client/**",
  "apps/client/**/*.test.tsx",
  "packages/db/test/**",
]
coverageReporter = [
  "text",
  "lcov"
]
coverageInclude = [
  "**/src/**/*.ts",
  "**/src/**/*.tsx"
]
coverageExclude = [
  "**/node_modules/**",
  "**/test/**",
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/index.ts",
  "**/types.ts",
  "**/*.d.ts",
]
