import type { ModelConfig } from '@excuse/shared'

export const MODELS: Record<string, ModelConfig> = {
  // ===== 文本生成模型 =====
  'qwen-max': {
    id: 'qwen-max',
    name: '千问 Max',
    category: 'text',
    type: 'generation',
    description: '阿里云最强文本生成模型，适合复杂任务',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation',
    async: false,
    pricing: { inputPrice: 2.4, outputPrice: 9.6, unit: 'token' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '输入文本' },
      { name: 'max_tokens', type: 'number', defaultValue: 1500, min: 1, max: 8000, description: '最大输出 Token 数' },
      { name: 'temperature', type: 'number', defaultValue: 0.7, min: 0, max: 2, description: '随机性控制' },
      { name: 'top_p', type: 'number', defaultValue: 0.9, min: 0, max: 1, description: '核采样参数' },
    ],
  },
  'qwen-plus': {
    id: 'qwen-plus',
    name: '千问 Plus',
    category: 'text',
    type: 'generation',
    description: '高性价比文本生成模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation',
    async: false,
    pricing: { inputPrice: 0.8, outputPrice: 2, unit: 'token' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '输入文本' },
      { name: 'max_tokens', type: 'number', defaultValue: 1500, min: 1, max: 8000, description: '最大输出 Token 数' },
      { name: 'temperature', type: 'number', defaultValue: 0.7, min: 0, max: 2, description: '随机性控制' },
    ],
  },
  'qwen-turbo': {
    id: 'qwen-turbo',
    name: '千问 Turbo',
    category: 'text',
    type: 'generation',
    description: '超高速文本生成模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation',
    async: false,
    pricing: { inputPrice: 0.3, outputPrice: 0.6, unit: 'token' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '输入文本' },
      { name: 'max_tokens', type: 'number', defaultValue: 1500, min: 1, max: 8000, description: '最大输出 Token 数' },
    ],
  },
  'qwen-long': {
    id: 'qwen-long',
    name: '千问 Long',
    category: 'text',
    type: 'generation',
    description: '超长上下文文本生成模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation',
    async: false,
    pricing: { inputPrice: 0.5, outputPrice: 2, unit: 'token' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '输入文本' },
      { name: 'max_tokens', type: 'number', defaultValue: 1500, min: 1, max: 8000, description: '最大输出 Token 数' },
    ],
  },

  // ===== 文生图模型 =====
  'qwen-image-2.0-pro': {
    id: 'qwen-image-2.0-pro',
    name: '千问图像 2.0 Pro',
    category: 'image',
    type: 'generation',
    description: '最强图像生成模型，擅长复杂文本渲染',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation',
    async: false,
    pricing: { inputPrice: 0.25, unit: 'image', note: '0.25元/张' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '正向提示词' },
      { name: 'negative_prompt', type: 'text', description: '反向提示词' },
      { name: 'size', type: 'select', defaultValue: '2048*2048', description: '图像分辨率', options: [
        { label: '2048x2048 (1:1)', value: '2048*2048' },
        { label: '2688x1536 (16:9)', value: '2688*1536' },
        { label: '1536x2688 (9:16)', value: '1536*2688' },
        { label: '2368x1728 (4:3)', value: '2368*1728' },
        { label: '1728x2368 (3:4)', value: '1728x2368' },
      ] },
      { name: 'n', type: 'number', defaultValue: 1, min: 1, max: 6, description: '生成数量' },
      { name: 'watermark', type: 'boolean', defaultValue: false, description: '添加水印' },
      { name: 'prompt_extend', type: 'boolean', defaultValue: true, description: '智能改写提示词' },
    ],
  },
  'qwen-image-max': {
    id: 'qwen-image-max',
    name: '千问图像 Max',
    category: 'image',
    type: 'generation',
    description: '高真实感图像生成模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation',
    async: false,
    pricing: { inputPrice: 0.25, unit: 'image', note: '0.25元/张' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '正向提示词' },
      { name: 'negative_prompt', type: 'text', description: '反向提示词' },
      { name: 'size', type: 'select', defaultValue: '1664*928', description: '图像分辨率', options: [
        { label: '1664x928 (16:9)', value: '1664*928' },
        { label: '1472x1104 (4:3)', value: '1472*1104' },
        { label: '1328x1328 (1:1)', value: '1328*1328' },
        { label: '1104x1472 (3:4)', value: '1104x1472' },
        { label: '928x1664 (9:16)', value: '928x1664' },
      ] },
      { name: 'watermark', type: 'boolean', defaultValue: false, description: '添加水印' },
      { name: 'prompt_extend', type: 'boolean', defaultValue: true, description: '智能改写提示词' },
    ],
  },

  // ===== 文生视频模型 =====
  'happyhorse-1.0-t2v': {
    id: 'happyhorse-1.0-t2v',
    name: 'HappyHorse 文生视频',
    category: 'video',
    type: 'generation',
    description: '高质量文生视频模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.9, inputPrice1080: 1.6, unit: 'video', note: '720P: 0.9元/秒, 1080P: 1.6元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '文本提示词' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.9元/秒)', value: '720P' },
        { label: '1080P (1.6元/秒)', value: '1080P' },
      ] },
      { name: 'ratio', type: 'select', defaultValue: '16:9', description: '宽高比', options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
      ] },
      { name: 'duration', type: 'number', defaultValue: 5, min: 3, max: 15, description: '视频时长（秒）' },
      { name: 'watermark', type: 'boolean', defaultValue: true, description: '添加水印' },
    ],
  },
  'happyhorse-1.0-i2v': {
    id: 'happyhorse-1.0-i2v',
    name: 'HappyHorse 图生视频',
    category: 'video',
    type: 'generation',
    description: '基于首帧图像生成视频',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.9, inputPrice1080: 1.6, unit: 'video', note: '720P: 0.9元/秒, 1080P: 1.6元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', description: '文本提示词' },
      { name: 'first_frame_url', type: 'text', description: '首帧图像URL' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.9元/秒)', value: '720P' },
        { label: '1080P (1.6元/秒)', value: '1080P' },
      ] },
      { name: 'duration', type: 'number', defaultValue: 5, min: 3, max: 15, description: '视频时长（秒）' },
      { name: 'watermark', type: 'boolean', defaultValue: true, description: '添加水印' },
    ],
  },
  'happyhorse-1.0-r2v': {
    id: 'happyhorse-1.0-r2v',
    name: 'HappyHorse 参考生视频',
    category: 'video',
    type: 'generation',
    description: '参考图像/视频生成多角色视频',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.9, inputPrice1080: 1.6, unit: 'video', note: '720P: 0.9元/秒, 1080P: 1.6元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '文本提示词' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.9元/秒)', value: '720P' },
        { label: '1080P (1.6元/秒)', value: '1080P' },
      ] },
      { name: 'duration', type: 'number', defaultValue: 5, min: 3, max: 15, description: '视频时长（秒）' },
      { name: 'watermark', type: 'boolean', defaultValue: true, description: '添加水印' },
    ],
  },
  'happyhorse-1.0-video-edit': {
    id: 'happyhorse-1.0-video-edit',
    name: 'HappyHorse 视频编辑',
    category: 'video',
    type: 'editing',
    description: '视频编辑模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.9, inputPrice1080: 1.6, unit: 'video', note: '720P: 0.9元/秒, 1080P: 1.6元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '编辑指令' },
      { name: 'video_url', type: 'text', required: true, description: '原视频URL' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.9元/秒)', value: '720P' },
        { label: '1080P (1.6元/秒)', value: '1080P' },
      ] },
      { name: 'watermark', type: 'boolean', defaultValue: true, description: '添加水印' },
    ],
  },
  'wan2.7-t2v': {
    id: 'wan2.7-t2v',
    name: '万相 2.7 文生视频',
    category: 'video',
    type: 'generation',
    description: '最新万相文生视频模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.6, inputPrice1080: 1, unit: 'video', note: '720P: 0.6元/秒, 1080P: 1元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '文本提示词' },
      { name: 'negative_prompt', type: 'text', description: '反向提示词' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.6元/秒)', value: '720P' },
        { label: '1080P (1元/秒)', value: '1080P' },
      ] },
      { name: 'ratio', type: 'select', defaultValue: '16:9', description: '宽高比', options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
      ] },
      { name: 'duration', type: 'number', defaultValue: 5, min: 2, max: 15, description: '视频时长（秒）' },
      { name: 'prompt_extend', type: 'boolean', defaultValue: true, description: '智能改写提示词' },
      { name: 'watermark', type: 'boolean', defaultValue: false, description: '添加水印' },
    ],
  },
  'wan2.7-i2v': {
    id: 'wan2.7-i2v',
    name: '万相 2.7 图生视频',
    category: 'video',
    type: 'generation',
    description: '基于首帧/首尾帧/视频片段生成视频',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.6, inputPrice1080: 1, unit: 'video', note: '720P: 0.6元/秒, 1080P: 1元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', description: '文本提示词' },
      { name: 'negative_prompt', type: 'text', description: '反向提示词' },
      { name: 'media_type', type: 'select', defaultValue: 'first_frame', description: '媒体类型', options: [
        { label: '首帧生视频', value: 'first_frame' },
        { label: '首尾帧生视频', value: 'first_last_frame' },
        { label: '视频续写', value: 'first_clip' },
      ] },
      { name: 'first_frame_url', type: 'text', description: '首帧图像URL' },
      { name: 'last_frame_url', type: 'text', description: '尾帧图像URL' },
      { name: 'video_url', type: 'text', description: '视频片段URL' },
      { name: 'audio_url', type: 'text', description: '驱动音频URL' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.6元/秒)', value: '720P' },
        { label: '1080P (1元/秒)', value: '1080P' },
      ] },
      { name: 'duration', type: 'number', defaultValue: 5, min: 2, max: 15, description: '视频时长（秒）' },
      { name: 'prompt_extend', type: 'boolean', defaultValue: true, description: '智能改写提示词' },
      { name: 'watermark', type: 'boolean', defaultValue: false, description: '添加水印' },
    ],
  },
  'wan2.7-r2v': {
    id: 'wan2.7-r2v',
    name: '万相 2.7 参考生视频',
    category: 'video',
    type: 'generation',
    description: '参考图像/视频生成多角色互动视频',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.6, inputPrice1080: 1, unit: 'video', note: '720P: 0.6元/秒, 1080P: 1元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '文本提示词' },
      { name: 'negative_prompt', type: 'text', description: '反向提示词' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.6元/秒)', value: '720P' },
        { label: '1080P (1元/秒)', value: '1080P' },
      ] },
      { name: 'ratio', type: 'select', defaultValue: '16:9', description: '宽高比', options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
      ] },
      { name: 'duration', type: 'number', defaultValue: 5, min: 2, max: 15, description: '视频时长（秒）' },
      { name: 'prompt_extend', type: 'boolean', defaultValue: true, description: '智能改写提示词' },
      { name: 'watermark', type: 'boolean', defaultValue: false, description: '添加水印' },
    ],
  },
  'wan2.7-videoedit': {
    id: 'wan2.7-videoedit',
    name: '万相 2.7 视频编辑',
    category: 'video',
    type: 'editing',
    description: '视频编辑模型',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    async: true,
    pricing: { inputPrice: 0.6, inputPrice1080: 1, unit: 'video', note: '720P: 0.6元/秒, 1080P: 1元/秒' },
    parameters: [
      { name: 'prompt', type: 'text', required: true, description: '编辑指令' },
      { name: 'video_url', type: 'text', required: true, description: '原视频URL' },
      { name: 'resolution', type: 'select', defaultValue: '720P', description: '视频分辨率', options: [
        { label: '720P (0.6元/秒)', value: '720P' },
        { label: '1080P (1元/秒)', value: '1080P' },
      ] },
      { name: 'watermark', type: 'boolean', defaultValue: false, description: '添加水印' },
    ],
  },
}

export function getModelById(id: string): ModelConfig | undefined {
  return MODELS[id]
}

export function getModelsByCategory(category: string): ModelConfig[] {
  return Object.values(MODELS).filter(m => m.category === category)
}
